name: slang_flutter
description: Flutter support for slang. This library provides helpful Flutter API.
version: 3.22.0
repository: https://github.com/slang-i18n/slang

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use tight version to ensure that all features are available
  slang: ../slang
